### ISSUE TITLE
Date scale on planisphere mislabeled?

### ISSUE THREAD

**Issue by davidwcraig** [dcf21/precession#1]
I think the date scale on the planisphere may be mislabeled, perhaps flipped around 2000 CE.
For instance, if the year is set to 2000 BCE, this puts the celestial pole (center of window) in Cepheus, whereas according to the chart on the website, the NCP is in Cepheus in 6000CE.

**Comment by dcf21** [comment]
Thanks a lot for this. At some point it does appear I accidentally flipped the scale, which is rather embarrassing.

I've just committed an update which should hopefully have fixed this.
